version: "3.8"

services:
  database:
    container_name: database
    image: postgres:12.8
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
      - POSTGRES_URL=postgresql://crud:pg@pass:5432
    ports:
      - 5432:5432
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: DEV
    ports:
      - 8000:8000
    volumes:
      - ./:/opt
volumes:
  db: